### ISSUE TITLE
Use recent API updates

### ISSUE THREAD

**Issue by calumhalcrow** [GovWizely/backbone-search-app#1]
This includes removing the use of "and" as the empty search string.

From David:

"https://pluto.kerits.org/v1/articles/count

https://pluto.kerits.org/v1/articles/search?countries=thailand,singapore&industries=aerospace+and+defense,agribusiness&topics=trade+development+and+promotion

Search requires one of the following parameters:
- q (no longer required)
- countries
- industries
- topics"

**Comment by calumhalcrow** [comment]
This was the second round of feedback from David:

"The types parameter is optional.
By default, it will search across all types.

On Mon, Nov 2, 2015 at 9:49 AM, David Pranata david@eigenpath.com wrote:
https://pluto.kerits.org/v1/articles/search?q=trade&types=country+commercial+guide,top+markets+report
https://pluto.kerits.org/v1/articles/search?q=trade&types=top+markets+report
https://pluto.kerits.org/v1/articles/search?q=trade&types=country+commercial+guide

You also get types aggregation on the count endpoint
https://pluto.kerits.org/v1/articles/count"

**Comment by calumhalcrow** [comment]
BTW, this has maybe already been done (or is just an invalid story). If either is the case @viclim please close this.

**Comment by viclim** [comment]
Done. See PR https://github.com/GovWizely/market-intelligence-search-app/pull/19
