### ISSUE TITLE
Apply feedback from Erik/team

### ISSUE THREAD

**Issue by calumhalcrow** [GovWizely/backbone-search-app#15]
![search_market_intelligence 1](https://cloud.githubusercontent.com/assets/277504/10929117/74a98512-82ea-11e5-8ba6-7edb649d0352.png)
![search_market_intelligence](https://cloud.githubusercontent.com/assets/277504/10929116/74a5fab4-82ea-11e5-9db1-126eb5f467a3.png)

**Comment by calumhalcrow** [comment]
Still todo on this issue:
- [x] search results should show up if the search form is submitted without a search query. (This is indicated by the "Search should activate on return. Currently you have to activate search box and hit return. Reason: you should be able to more easily search by Country and / or Industy w/o a keyword." text).
- [x] show search result source field in results.

**Comment by viclim** [comment]
``` js
{
      "countries": [
        "Taiwan"
      ],
      "industries": [
        "Information and Communication Technology"
      ],
      "topics": [
        "Trade Development and Promotion"
      ],
      "type": "Country Commercial Guide", // <------ THIS IS SOURCE YA?
      "url": "http://apps.export.gov/article?id=Taiwan-electronics-production-and-test-equipment",
      "id": "ka0t0000000PGKKAA4",
      "title": "Taiwan – Electronics Industry Production and <em>Test</em> Equipment",
      "snippet": "...  consecutive year, according to SEMI. Taiwan’s lead is forecast to widen further this year with the figure projected to surge 28.14 percent to US$12.34 billion. Taiwan imports most of its advanced electronics industry production/<em>test</em> (EIP) equipment, with demand ..."
}
```

**Comment by calumhalcrow** [comment]
@viclim YA :D

**Comment by viclim** [comment]
Done. See PR https://github.com/GovWizely/market-intelligence-search-app/pull/19
