### ISSUE TITLE
Distinct search forms (keyword and industry/country).

### ISSUE THREAD

**Issue by calumhalcrow** [GovWizely/backbone-search-app#20]
The requirement is to make the homepage form behave as if it were two separate forms. One for keyword search and one for industry/country search. This requires the following changes:
- [x] Add another search button to the homepage, under the industry/country fields (like in the [original mockup](http://ajsingh273.github.io/km/home.html)).
- [x] Change the "And" text between the industry and country selects to "And / Or".
- [x] On the condensed form on the results page, we need to convey the same separation. So, add a search button next to the selects, something like this:
  ![screen shot 2015-11-06 at 9 48 12 am](https://cloud.githubusercontent.com/assets/277504/10987743/3481d8d0-8471-11e5-9554-7ec56a8b4ce2.png)
- [x] Change the "Advance Search" left panel heading text to "Filtered Results" [1].

[1] I don't think that this is the best choice of text here, but it was requested to be that so let's just go with it. I'm going to raise concern over that change on the story later...

**Comment by viclim** [comment]
Done. See PR https://github.com/GovWizely/market-intelligence-search-app/pull/19
