### ISSUE TITLE
Add .gitignore to gh-pages branch

### ISSUE THREAD

**Issue by calumhalcrow** [GovWizely/backbone-search-app#22]
Whenever I checkout gh-pages locally git makes my terminal fairly unresponsive due to it trying to tell me about the 78k untracked files in node_modules/, bower_components, etc. If they were ignored this wouldn't happen.

The tricky part of this task is to ensure that `gulp deploy` doesn't wipe away .gitignore.

**Comment by viclim** [comment]
Fixed. https://github.com/GovWizely/market-intelligence-search-app/pull/69
